### ISSUE TITLE
Expose `DBNames` as platform environment  variables

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/aqueduct#286]
The two DB names for the `postgresql` and `redshift` are currently only available if you know via a notebook Civis staff shared with us. 

Would like all users to have access to a `POSTGIS_URI` and  `REDSHIFT_URI` exposing their credentials to access the respective dbs. This should be a SQLAlchemy compatible URI string.

**Comment by ian-r-rose** [comment]
I've snooped around the civis APIs a bit and come up with this set of utility functions which allow you to create a sqlalchemy engine for the two DBs without knowing beforehand the host and credential id:

```python
from urllib.parse import urlparse, quote_plus

import sqlalchemy

def get_db_uri(kind, api_key=None):
    # List all the remote hosts, which include the DB instances
    client = civis.APIClient(api_key)
    hosts = client.remote_hosts.list()

    # Find the right DB
    db = next(h for h in hosts if h["type"] == kind)
    parsed = urlparse(db["url"].lstrip("jdbc:"))
    
    # Get the credentials from the environment
    credential = client.credentials.get(client.default_credential)
    user = quote_plus(os.environ[f"{credential['name'].upper()}_USERNAME"])
    password = quote_plus(os.environ[f"{credential['name'].upper()}_PASSWORD"])
    
    # Parse the URL and construct the SQLAlchemy URL.
    if "redshift" in parsed.scheme:
        scheme = "redshift+psycopg2"
    elif "postgres" in parsed.scheme:
        scheme = "postgres"

    uri = f"{scheme}://{user}:{password}@{parsed.netloc}{parsed.path}"
    return uri
                          
def get_postgres_engine(api_key=None):
    uri = get_db_uri("RemoteHostTypes::Postgres")
    return sqlalchemy.create_engine(uri)

def get_redshift_engine(api_key=None):
    uri = get_db_uri("RemoteHostTypes::Redshift")
    return sqlalchemy.create_engine(uri, connect_args={'sslmode': 'require'})
```

**Comment by juliaoran** [comment]
Added them as credentials to the robot account (can be accessed via parameters)

**Comment by ian-r-rose** [comment]
@juliaoran What do you think about the utility function above that uses the Civis API? That one has the benefit of not having to have a Civis employee manually add the hostname as credentials.

**Comment by hunterowens** [comment]
FYI this fails on my inside my civis notebook with

```

---------------------------------------------------------------------------KeyError
                                 Traceback (most recent call
last)<ipython-input-11-c539ec34e626> in <module>()----> 1
get_redshift_engine()
<ipython-input-10-1d56c4b1a7f0> in get_redshift_engine(api_key)     35
     36 def get_redshift_engine(api_key=None):---> 37     uri =
get_db_uri("RemoteHostTypes::Redshift")     38     return
sqlalchemy.create_engine(uri, connect_args={'sslmode': 'require'})
<ipython-input-10-1d56c4b1a7f0> in get_db_uri(kind, api_key)     18
 # Get the credentials from the environment     19     credential =
client.credentials.get(client.default_credential)---> 20     user =
quote_plus(os.environ[f"{credential['name'].upper()}_USERNAME"])
21     password =
quote_plus(os.environ[f"{credential['name'].upper()}_PASSWORD"])
22
/opt/conda/lib/python3.7/os.py in __getitem__(self, key)    677
 except KeyError:    678             # raise KeyError with the
original key value--> 679             raise KeyError(key) from None
680         return self.decodevalue(value)    681
KeyError: 'HOWENS1_USERNAME'
```

**Comment by juliaoran** [comment]
> @juliaoran What do you think about the utility function above that uses the Civis API? That one has the benefit of not having to have a Civis employee manually add the hostname as credentials.

Hi @ian-r-rose -- from what I can tell, in theory that should work re:getting the hostname. From @hunterowens error above, I'm wondering if that section getting the credential doesn't work because (and possible I am wrong here) I think to reference it as a env var it has to be a parameter in the script?? (At least that's how I've seen it done before)

Sorry, I haven't spent a lot of time in the API, so @akoebs please chime in if you have thoughts!

**Comment by hunterowens** [comment]
@hunterowens to post link to script that fails

**Comment by hunterowens** [comment]
my [notebook](https://platform.civisanalytics.com/spa/#/notebooks/16851)

**Comment by akoebs** [comment]
Hey all, 

Just wanted to update that I'm still looking into this, and chatting with some of our engineers who are more familiar with the API.  I can't get this behavior to work on various account types so it isn't a permissions problem.  I _believe_ it is something Julia alluded too, especially with regards to how passwords can be surfaced and that a workaround would be be using a passed credential as an env var, but that would sorta defeat the purpose.  I could be off here, but will keep you updated!

Cheers,

Alex

**Comment by ian-r-rose** [comment]
@hunterowens I don't have permissions to view your sample notebook, but might it be as simple as your `howens1` credentials not being attached to the civis object? My utility could definitely be more fault-tolerant, but it does rely on the db credentials being available.

**Comment by ian-r-rose** [comment]
Another update here: it looks like when you add a database parameter to container scripts, the environment variables that we need are injected into the environment:

![image](https://user-images.githubusercontent.com/5728311/83193911-a5a4fa00-a0ec-11ea-8806-09a9c1aebe42.png)

This seems like the simplest way forward for the case that we are using container scripts. I'm not sure if this also happens for scripts or notebooks at the moment.

Any thoughts @akoebs?

**Comment by juliaoran** [comment]
@ian-r-rose -- yeah, I had suggested adding a parameter above, but maybe that got lost in the chatter. That should work for all scripts (container or otherwise). I don't believe there is the same parameter functionality for notebooks, but @akoebs might know more.

**Comment by ian-r-rose** [comment]
Ah, I had misunderstood what you meant above @juliaoran, thanks for the update.

**Comment by juliaoran** [comment]
@ian-r-rose oh sorry about!

**Comment by ian-r-rose** [comment]
> 
> 
> Added them as credentials to the robot account (can be accessed via parameters)

Actually @juliaoran, I'm still not sure what you mean by this. I was able to access the database hostname using the parameter types for a container script (by selecting "`Database (2 dropdowns)`") from the options. I was then able to select the credentials for my own account, rather than the robot account (I still haven't really figured out how to assume the robot role, actually).

The above seems different to me from selecting credentials from the robot account. Or do I still misunderstand what you mean?

**Comment by juliaoran** [comment]
Hi @ian-r-rose,

To assume the robot role, go to Admin > Users. When you hover over the robot, you'll see an Assume Role button pop up. Once you click Assume Role, you'll be able to do work as the robot. To resume your role, click the initials in the top right and select Resume Original Role. Sorry, if you've tried this before and it didn't work -- I just realized you didn't have the correct permissions and updated them.

<img width="1141" alt="Screen Shot 2020-05-29 at 11 06 28 AM" src="https://user-images.githubusercontent.com/56890581/83275767-a21d7b80-a19d-11ea-90ef-efe460c12c80.png">

I didn't realize that the database hostname was exposed through that parameter, so that's definitely a valid solution. What I had done was add the hostnames as passwords for credentials on the robot account. You can access those values by adding a custom credential parameter and accessing its password. I created an example here (first you'll have to assume the robot's role): https://platform.civisanalytics.com/spa/#/scripts/python3/77330171

**Comment by ian-r-rose** [comment]
Okay, thanks for the explanation. To recap, I think we have now identified a few different solutions for this issue, which might be useful in different contexts:
1. Attach a "database" parameter to a script
1. Use the hostname provided in a custom credential (like the one @juliaoran added to the robot account)
1. Use the utility function I wrote in a notebook (requires the database credentials to be attached to a notebook session).

I think that this issue can be closed, thanks for all the help.
